noises:
  gps_std: 0.1 # m

settings:
  ###################
  # Filter Settings #
  ###################
  translation_imu2body: [0, 0, 0] # Translation vector points from body center to the imu. Defined in body frame[x, y, z]
  rotation_imu2body: [1, 0, 0, 0] # Orientation from IMU to the body frame. [w, x, y, z]
  gps_scale: 1.0
  correction_time_threshold: 0.3